[package]
name = "webart-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy-regex = "2.2.1"
markdown-to-html = "0.1.1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
